# Generated by Django 2.2.7 on 2019-12-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='news',
            name='country',
        ),
        migrations.AddField(
            model_name='news',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Country'),
            preserve_default=False,
        ),
    ]
